#ifndef _TYPEID_H
#define _TYPEID_H

#define UNKNOWN			0
#define NODE_TYPE_INT		1
#define NODE_TYPE_DOUBLE	2
#define NODE_TYPE_IDENT		3
#define NODE_TYPE_STRING	4
#define NODE_TYPE_CALL		5
#define NODE_TYPE_BINOP		6
#define NODE_TYPE_ASSIGN	7
#define NODE_TYPE_BLOCK		8
#define NODE_TYPE_EXPR_STMT	9
#define NODE_TYPE_VAR_DECL	10
#define NODE_TYPE_FUNC		11
#define NODE_TYPE_IF		12
#define NODE_TYPE_WHILE		13
#define NODE_TYPE_FOR		14
#define NODE_TYPE_RETURN	15

#endif
